# Generated by Django 6.0.4 on 2026-04-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_record', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='consultationrecord',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
